pex:
  enabled: false
  file: permissions.yml
essentials:
  enabled: false
  days: 60
players:
  enabled: true
  days: 60
  setLocation:
    enabled: false
    x: 0
    y: 0
    z: 0
    world: world
disableAll: true